import Vue from 'vue';
import {DatePicker} from 'ant-design-vue';
import {Button} from 'ant-design-vue';
import {Drawer} from 'ant-design-vue';
import {Menu} from 'ant-design-vue';
import {Avatar} from 'ant-design-vue';
import {Popover} from 'ant-design-vue';
import {List} from 'ant-design-vue';
import {Icon} from 'ant-design-vue';
import {Layout} from 'ant-design-vue';

Vue.use(Button);
Vue.use(DatePicker);
Vue.use(Drawer);
Vue.use(Menu);
Vue.use(Avatar);
Vue.use(Popover);
Vue.use(List);
Vue.use(Icon);
Vue.use(Layout);
